yet another debuug test

diff --git a/.github/workflows/NepflowTestAction.yml b/.github/workflows/NepflowTestAction.yml
--- a/.github/workflows/NepflowTestAction.yml
+++ b/.github/workflows/NepflowTestAction.yml
@@ -25,7 +25,20 @@ jobs:
         with:
               java-version: '21'
               distribution: 'zulu'
+              
+              
+      - name: Check if JASYPT_ENCRYPTOR_PASSWORD is set
+        env:
+            JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
+
+        run: |
+          if [ -z "$JASYPT_ENCRYPTOR_PASSWORD" ]; then
+            echo "Error: Environment variable 'JASYPT_ENCRYPTOR_PASSWORD' is not set. Please set the environment variable or pass it as a secret."
+            exit 1
+          else
+            echo "Environment variable 'JASYPT_ENCRYPTOR_PASSWORD' is set."
+          fi
       - name: execute Tests
         env:
             JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
-        run:  cd nepflow && chmod +x gradlew && ./gradlew test --tests "com.nepflow.*" -P password="$JASYPT_ENCRYPTOR_PASSWORD" 
+        run:  cd nepflow && chmod +x gradlew && ./gradlew test --tests "com.nepflow.*" -P password="$JASYPT_ENCRYPTOR_PASSWORD"
